apiVersion: apps/v1
kind: Deployment
metadata :
  name: frontend-deployment
  labels:
    app: frontend
spec:
  template:
    metadata:
      name: pod-my-nginx
      labels:
        env: production
    spec:
       containers: 
         - name: nginx-container
           image: nginx
  selector:
    matchLabels:
      env: production 
  strategy:
     ## Rolling Update: Atualização gradual dos pods, sem downtime
     ## Recreate: Destrói todos os pods existentes e cria novos
     ## Blue/Green: Cria um novo deployment e atualiza o old deployment
     ## Canary: Atualização gradual dos pods, com downtime
     ## A/B Testing: Atualização gradual dos pods, com downtime
    type: Recreate
  replicas: 1
